#!/bin/bash
# Use this file (on a unix system) to generate the zip archive for CTAN
# ctanify is part of TeX Live and MiKTeX distributions
# Please note, that you need at least version 1.9 to add the symbolic link correctly.
#
echo "Make sure we have the latest version"
pdflatex cidarticle.dtx
echo "Make sure all links in cidarticle.pdf are correct"
pdflatex cidarticle.dtx
if [ -f cidarticle.tar.gz ]; then
   echo "Remove old archive"
   rm cidarticle.tar.gz
fi
ctanify --no-tds cidarticle.ins cidarticle.pdf README.md CHANGELOG.md CONTRIBUTING.md "cidarticle.pdf=doc/latex/cidarticle" "cidarticle-author-template.tex=doc/latex/cidarticle" "cidarticle-example.bib=doc/latex/cidarticle"
